### PR TITLE
Fix: issue with with cl-preload and ert causing test failures on emacs 25.1

### PR DESCRIPTION
**Pull request by davidshepherd7**

### CODE REVIEW

**Comment by rejeep** [comment]
Looks good.

Also, I invited you to the Ecukes org. You seem to know your way around the repos. That said, I still think PRs the way to go before merging code, so I'm happy to review them before you merge them.

**Comment by davidshepherd7** [comment]
Oh I think I misunderstood you, was I supposed to be merging this myself? I don't think I can at the moment: I don't have write access.

**Comment by rejeep** [comment]
Can you try now and see if you have access?

**Comment by davidshepherd7** [comment]
Yep :)

Do you prefer rebases or merges usually?

**Comment by rejeep** [comment]
Nice! 👍

I'm not a big fan of rebase, but we use it at work, so I use it in my projects as well.

**Pull request merged**
