### PR TITLE
Feature When I call

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
new step to call a command without having to ply with the action chain. :)

### CODE REVIEW

**Comment by rejeep** [comment]
If we are going to add this feature, I think we should add another test case. To start a major mode, you should use https://github.com/ecukes/espuds/blob/master/espuds.el#L319-L323

**Comment by AdrieanKhisbe** [comment]
Indeed, wasn't that inspired when I wrote the test ^^

**Comment by AdrieanKhisbe** [comment]
being again not that inspired I end up having a look to the test that was before. so I went to play with the windows :)

**Comment by rejeep** [comment]
Can you please squish all these commands into one?

**Comment by AdrieanKhisbe** [comment]
*voili voilou :)*

**Comment by rejeep** [comment]
Actually, can you choose another function so that in can be run in `--script` mode. Now you get: _"too small for splitting 2"_

**Comment by AdrieanKhisbe** [comment]
now we just insert parentheses :)

**Comment by rejeep** [comment]
Thanks, merged, sorry for the delay!

**Comment by AdrieanKhisbe** [comment]
no problemo :)

**Pull request merged**
