### PR TITLE
Update .travis.yml for emacs 25

### PR DESCRIPTION
**Pull request by davidshepherd7**

### CODE REVIEW

**Comment by rejeep** [comment]
The tests doesn't actually pass, wanna take a look?

**Comment by davidshepherd7** [comment]
Looks like it might be a bug way down in emacs.

The problem seems to be that ert's "fake" debugger (which it uses to get error information) is not being called, and the default debugger is being called instead.

I think this is happening because [`cl--assertion-failed`](https://github.com/emacs-mirror/emacs/blob/emacs-25.1/lisp/emacs-lisp/cl-preloaded.el#L46) (which is called when a `cl-assert` fails) calls the default debugger directly.

This is probably also the reason that ecukes test failures print out huge unreadable stack traces when an assert fails.

**Comment by davidshepherd7** [comment]
Just to confirm that: [here](https://github.com/davidshepherd7/espuds/commit/07a479a8ecb39e5f0b7342f7951257572809bcba) is a patch which "fixes" the problem by monkey-patching `cl--assertion-failed` to not do the strange debugger call. Obviously it isn't a real fix, but I think it proves that this is the problem.

**Comment by davidshepherd7** [comment]
This should be [fixed](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=24778) in 25.2.

**Comment by rejeep** [comment]
Nice job! 👍 

One way to solve running the specs in 25.1 I guess is to tag that test with _"do not run in Emacs 25.1"_ and then exclude that tag when running the tests in that Emacs version.

**Comment by davidshepherd7** [comment]
Unfortunately I think quite a not of the tests will fail because the
problem is so low level.

If we want to be able to test on 25.1 I think the best approach would be to
fix the problem itself, either with an advice (as I think someone wrote in
the bug's email thread) or by replacing the broken function (with the code
I posted above). We would only apply the changes in emacs 25 and only in
the test code, so it wouldn't be too much of an awful hack.

**Comment by davidshepherd7** [comment]
*quite a lot

**Comment by rejeep** [comment]
Ok, I'm fine with that too!

**Comment by davidshepherd7** [comment]
Closed in favor of #45

**Pull request closed without merging**
